First attempt at SQL lite and PeeWee
I've been struggling with this for a while now. Any help with the sorting out the following error would be appreciated:

INFO:personjobdept_model:Here we define our data (the schema)
INFO:personjobdept_model:First name and connect to a database (sqlite here)
INFO:personjobdept_model:The next 3 lines of code are the only database specific code
INFO:personjobdept_model:This means we can easily switch to a different database
INFO:personjobdept_model:Enable the Peewee magic! This base class does it all
INFO:personjobdept_model:By inheritance only we keep our model (almost) technology neutral
INFO:personjobdept_model:Note how we defined the class
INFO:personjobdept_model:Specify the fields in our model, their lengths and if mandatory
INFO:personjobdept_model:Must be a unique identifier for each person
INFO:personjobdept_model:The department name
INFO:personjobdept_model:The name of the manager
INFO:personjobdept_model:The number of the department
INFO:personjobdept_model:Now the Job class with a similar approach
INFO:personjobdept_model:Dates
INFO:personjobdept_model:Number
INFO:personjobdept_model:Which person had the Job
INFO:personjobdept_model:An alternate Person class
INFO:personjobdept_model:Note: no primary key so we're give one 'for free'
INFO:personjobdept_model:Creating the database: <peewee.SqliteDatabase object at 0x033DC0B0>
INFO:__main__:Working with Person class
INFO:__main__:Note how I use constants and a list of tuples as a simple schema
INFO:__main__:Normally you probably will have prompted for this from a user
INFO:__main__:Creating Person records: iterate through the list of tuples
INFO:__main__:Prepare to explain any errors with exceptions
INFO:__main__:and the transaction tells the database to fail on error
INFO:__main__:Database add successful
INFO:__main__:Database add successful
INFO:__main__:Database add successful
INFO:__main__:Database add successful
INFO:__main__:Database add successful
INFO:__main__:Print the Person records we saved...
INFO:__main__:Andrew lives in Sumner and likes to be known as Andy
INFO:__main__:Peter lives in Seattle and likes to be known as None
INFO:__main__:Susan lives in Boston and likes to be known as Beannie
INFO:__main__:Pam lives in Coventry and likes to be known as PJ
INFO:__main__:Steven lives in Colchester and likes to be known as None
INFO:__main__:database closes
INFO:__main__:Working with Department class
INFO:__main__:Creating Departnent records: just like Person. We use the foreign key
INFO:__main__:Reading and print all Departments rows...
INFO:__main__:ADMN : Pepper Potts manages Admin
INFO:__main__:PHOT : Peter Parker manages Photo
INFO:__main__:SUPR : Clark Kent manages Reporter
INFO:__main__:database closes
INFO:__main__:Working with Job class
INFO:__main__:Creating Job records: just like Person. We use the foreign key
INFO:__main__:Reading and print all Job rows (note the value of person)...
INFO:__main__:database closes
Traceback (most recent call last):
  File "C:\Users\Mike\AppData\Local\Programs\Python\Python37-32\lib\site-packages\peewee.py", line 5866, in get
    return clone.execute(database)[0]
  File "C:\Users\Mike\AppData\Local\Programs\Python\Python37-32\lib\site-packages\peewee.py", line 3638, in __getitem__
    return self.row_cache[item]
IndexError: list index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "F:/OneDrive/Programming/Python/Python Examples/Python 220 examples/Lesson 07/populate_dept.py", line 335, in populate_jobs
    logger.info(f'{job.job_name} : {job.start_date} to {job.end_date} for {job.person_employed} in {job.job_dept}')
  File "C:\Users\Mike\AppData\Local\Programs\Python\Python37-32\lib\site-packages\peewee.py", line 3786, in __get__
    return self.get_rel_instance(instance)
  File "C:\Users\Mike\AppData\Local\Programs\Python\Python37-32\lib\site-packages\peewee.py", line 3777, in get_rel_instance
    obj = self.rel_model.get(self.field.rel_field == value)
  File "C:\Users\Mike\AppData\Local\Programs\Python\Python37-32\lib\site-packages\peewee.py", line 5468, in get
    return sq.get()
  File "C:\Users\Mike\AppData\Local\Programs\Python\Python37-32\lib\site-packages\peewee.py", line 5871, in get
    (clone.model, sql, params))
personjobdept_model.DepartmentDoesNotExist: <Model: Department> instance matching query does not exist:
SQL: SELECT "t1"."dept_name", "t1"."dept_manager", "t1"."dept_number" FROM "department" AS "t1" WHERE ("t1"."dept_name" = ?) LIMIT ? OFFSET ?
Params: ['PHOT', 1, 0]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "F:/OneDrive/Programming/Python/Python Examples/Python 220 examples/Lesson 07/populate_dept.py", line 363, in <module>
    populate_jobs()
  File "F:/OneDrive/Programming/Python/Python Examples/Python 220 examples/Lesson 07/populate_dept.py", line 341, in populate_jobs
    logger.info(f'Error creating = {job[JOB_NAME]}')
TypeError: 'Job' object does not support indexing

Process finished with exit code 1


Thanks for any help you can provide.